# Spacy

### Models

Spacy comes with a variety of different models that can used per language. For instance, the models for English are available [here](https://spacy.io/models/en). You'll need to download each model separately:

```python
python3 -m spacy download en_core_web_sm
python3 -m spacy download en_core_web_md

```

## Pattern Matching Using Spacy

The below code and example is from Ashiq KS's article [Rule-Based Matching with spacy](https://medium.com/@ashiqgiga07/rule-based-matching-with-spacy-295b76ca2b68):

In [ ]:
#The input text string is converted to a Document object
text = '''
Computer programming is the process of writing instructions that get executed by computers. 
The instructions, also known as code, are written in a programming language which the computer 
can understand and use to perform a task or solve a problem. Basic computer programming involves 
the analysis of a problem and development of a logical sequence of instructions to solve it. 
There can be numerous paths to a solution and the computer programmer seeks to design and 
code that which is most efficient. Among the programmer’s tasks are understanding requirements, 
determining the right programming language to use, designing or architecting the solution, coding, 
testing, debugging and writing documentation so that the solution can be easily
understood by other programmers.Computer programming is at the heart of computer science. It is the 
implementation portion of software development, application development 
and software engineering efforts, transforming ideas and theories into actual, working solutions.
'''

In [ ]:
from spacy.matcher import Matcher #import Matcher class from spacy
#import the Span class to extract the words from the document object
from spacy.tokens import Span 

#Language class with the English model 'en_core_web_sm' is loaded
nlp = spacy.load("en_core_web_sm")

doc = nlp(text) # convert the string above to a document

#instantiate a new Matcher class object 
matcher = Matcher(nlp.vocab)

### Define the Target Pattern

The `pattern` object that you define should be a list of dictionary elements, each dictionary describing the token to match for. 

Here, we are matching for the usage of `computer` as a `NOUN`.

In [ ]:
#define the pattern
pattern = [{'LOWER': 'computer', 'POS': 'NOUN'},
             {'POS':{'NOT_IN': ['VERB']}}]


### Load the Pattern into the Matcher

In [ ]:
#add the pattern to the previously created matcher object
matcher.add("Matching", None, pattern)

## Using Regular Expressions in Spacy

The below example can be found at https://spacy.io/usage/rule-based-matching. It uses the `re.finditer()` function to
quickly iterate through all the matches found. 

In [1]:
import spacy
import re
nlp = spacy.load("en_core_web_sm")
doc = nlp("The United States of America (USA) are commonly known as the United States (U.S. or US) or America.")

expression = r"\b[Uu](nited|\.?) ?[Ss](tates|\.?)\b"
for match in re.finditer(expression, doc.text):
    start, end = match.span()
    span = doc.char_span(start, end)
    # This is a Span object or None if match doesn't map to valid token sequence
    if span is not None:
        print("Found match:", span.text)

Found match: United States
Found match: United States
Found match: US


## Part of Speech Tagging

In [ ]:
!python3 -m spacy download en_core_web_sm
!python3 -m spacy download en_core_web_md

In [2]:
import en_core_web_sm
import spacy
from scipy.spatial.distance import cosine
import spacy

nlp = spacy.load('en_core_web_md')

In [3]:
doc = nlp(u"Steve Jobs and Apple is looking at buying U.K. startup for $1 billion")

In [2]:
import pandas as pd
rows = []
doc = nlp(u"Steve Jobs and Apple is looking at buying U.K. startup for $1 billion")
for token in doc:
    rows.append((token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop))
    
data = pd.DataFrame(rows, columns=["text", "lemma", "part_of_speech", "tag", "dependency", "shape", "is_alphanumeric", "is_stopword"])
data.head()

text  lemma part_of_speech  tag dependency  shape  is_alphanumeric  \
0  Steve  Steve          PROPN  NNP   compound  Xxxxx             True   
1   Jobs   Jobs          PROPN  NNP      nsubj   Xxxx             True   
2    and    and          CCONJ   CC         cc    xxx             True   
3  Apple  Apple          PROPN  NNP       conj  Xxxxx             True   
4     is     be            AUX  VBZ        aux     xx             True   

   is_stopword  
0        False  
1        False  
2         True  
3        False  
4         True

### Named Entity Recognition

In [ ]:
# example from spacy docs
doc = nlp(u"Steve Jobs and Apple is looking at buying U.K. startup for $1 billion")
import en_core_web_sm
import spacy
from scipy.spatial.distance import cosine
nlp = en_core_web_sm.load()

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

In [ ]:
# visualize this using displacy:
from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

# Word Embeddings (word2vec Introduction) from Intro to Algorithmic Marketing

## Continuous Bag of Words (Use Context to Predict Target Word)
![alt text](https://raw.githubusercontent.com/ychennay/dso-560-nlp-text-analytics/main/images/word2vec_cbow.png "Logo Title Text 1")

## Softmax
![alt text](https://raw.githubusercontent.com/ychennay/dso-560-nlp-text-analytics/main/images/softmax.png "Logo Title Text 1")

## Skipgram
![alt text](https://raw.githubusercontent.com/ychennay/dso-560-nlp-text-analytics/main/images/skipgram.png "Logo Title Text 1")

## Softmax
![alt text](https://raw.githubusercontent.com/ychennay/dso-560-nlp-text-analytics/main/images/wordembedding_cluster.png "Logo Title Text 1")

In [7]:
for token in nlp("cake pie cookie"):
    for token2 in nlp("cake pie cookie")

[-2.5035 -4.4334 -3.5839 -1.1924 -2.6549]
[ 3.9661 -3.784  -1.7973  4.8387 -3.1422]
[ 1.6477  -0.62039  0.49445  0.59497  0.21123]


In [ ]:
import en_core_web_sm
import en_core_web_md
import spacy
from scipy.spatial.distance import cosine
nlp = en_core_web_sm.load()

In [8]:
tokens = nlp(u'dog cat Beijing sad depressed couch sofa canine China Chinese France Paris banana')

for token1 in tokens:
    for token2 in tokens:
        if token1 != token2:
            print(f" {token1} - {token2}: {1 - cosine(token1.vector, token2.vector)}")

 dog - cat: 0.8220816850662231
 dog - Beijing: 0.002425447339192033
 dog - sad: 0.07570135593414307
 dog - depressed: 0.03279789537191391
 dog - couch: 0.3259493410587311
 dog - sofa: 0.23664459586143494
 dog - canine: 0.719451904296875
 dog - China: -0.04230016842484474
 dog - Chinese: -0.029234278947114944
 dog - France: -0.06262815743684769
 dog - Paris: -0.05884140357375145
 dog - banana: 0.2090904712677002
 cat - dog: 0.8220816850662231
 cat - Beijing: -0.01780039817094803
 cat - sad: 0.1828613430261612
 cat - depressed: 0.03235473856329918
 cat - couch: 0.38777071237564087
 cat - sofa: 0.31662240624427795
 cat - canine: 0.6167997121810913
 cat - China: -0.004194827750325203
 cat - Chinese: 0.005479123443365097
 cat - France: -0.12037640064954758
 cat - Paris: -0.026788583025336266
 cat - banana: 0.2235882729291916
 Beijing - dog: 0.002425447339192033
 Beijing - cat: -0.01780039817094803
 Beijing - sad: -0.07578963041305542
 Beijing - depressed: 0.15482419729232788
 Beijing - couc

# Finding Most Similar Words (Using Our Old Methods)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

# inspect the default settings for CountVectorizer
CountVectorizer()

CountVectorizer()

In [6]:
import pandas as pd
reviews = open("../datasets/poor_amazon_toy_reviews.txt").readlines()

vectorizer = CountVectorizer(ngram_range=(1, 1), 
                             stop_words="english", 
                             max_features=500,token_pattern='(?u)\\b[a-zA-Z][a-zA-Z]+\\b')
X = vectorizer.fit_transform(reviews)

data = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())
data.head()

/Users/yuchen/Library/Python/3.9/lib/python/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


able  absolutely  actual  actually  adult  advertised  ago  air  amazon  \
0     0           0       0         0      0           0    0    0       0   
1     0           0       0         0      0           0    0    0       0   
2     0           0       0         0      0           0    0    0       0   
3     0           0       0         0      0           0    0    0       0   
4     0           0       0         0      0           1    0    0       0   

   apart  ...  working  works  worse  worst  worth  wouldn  wrong  year  \
0      0  ...        0      0      0      0      0       0      0     0   
1      0  ...        0      0      0      0      0       0      0     0   
2      0  ...        0      0      0      0      0       0      0     0   
3      0  ...        0      0      0      0      0       0      0     0   
4      0  ...        0      0      0      0      0       0      0     0   

   years  zero  
0      0     0  
1      0     0  
2      0     0  
3      0     0  
4      0     0  

[5 rows x 500 columns]

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

# create similiarity matrix
similarity_matrix = pd.DataFrame(cosine_similarity(data.T.values), 
             columns=vectorizer.get_feature_names(),
                                 index=vectorizer.get_feature_names())

/Users/yuchen/Library/Python/3.9/lib/python/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [8]:
# unstack matrix into table
similarity_table = similarity_matrix.rename_axis(None).rename_axis(None, axis=1).stack().reset_index()

In [9]:
# rename columns
similarity_table.columns = ["word1", "word2", "similarity"]
similarity_table.shape

(250000, 3)

In [10]:
similarity_table = similarity_table[similarity_table["similarity"] < 0.99]
similarity_table.shape

(249500, 3)

In [11]:
similarity_table.sort_values(by="similarity", ascending=False).drop_duplicates(
    subset="similarity", keep="first").head(10)

word1     word2  similarity
144497      old      year    0.754569
194593  service  customer    0.734095
237276    waste     money    0.655483
245419  working   stopped    0.589414
74650    figure   figures    0.553856
5949        arm     train    0.500379
172826  quality      poor    0.469081
179083   remote   control    0.456930
210121    store    dollar    0.426935
4648      apart      fell    0.385922

In [12]:
top_500_words = vectorizer.get_feature_names()

/Users/yuchen/Library/Python/3.9/lib/python/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# Exercise: Similar Words Using Word Embeddings

In [13]:
# load into spacy your top 500 words

tokens = nlp(f'{" ".join(top_500_words)}')

In [14]:
from itertools import product
# create a list of similarity tuples

similarity_tuples = []

for token1, token2 in product(tokens, repeat=2):
    similarity_tuples.append((token1, token2, token1.similarity(token2)))

similarities = pd.DataFrame(similarity_tuples, columns=["word1","word2", "score"])


In [15]:
# find similar words
similarities[similarities["score"] < 1].sort_values(
    by="score", ascending=False).drop_duplicates(
    subset="score", keep="first").head(5)

word1          word2     score
150235  overpriced      expensive  1.000000
54728         didn           aren  1.000000
242244       weeks         months  0.945185
48876     daughter  granddaughter  0.939131
218073    terrible       horrible  0.934416

## Finding The Most Similar Documents

#### Using Count Vectorizer

In [21]:
N = 500
doc_similarities = pd.DataFrame(cosine_similarity(data[:500].values))

In [28]:
doc_similarity_table = doc_similarities.rename_axis("doc1").rename_axis("doc2", axis=1).stack().reset_index()
doc_similarity_table.columns = ["doc1", "doc2", "similarity"]
doc_similarity_table = doc_similarity_table[doc_similarity_table["similarity"] < 0.99]

In [30]:
doc_similarity_table.sort_values(by="similarity", ascending=False).drop_duplicates(
    subset="similarity", keep="first").head(10)

doc1  doc2  similarity
54002    108     2    0.944911
223406   446   406    0.894427
195639   391   139    0.866025
103311   206   311    0.816497
223261   446   261    0.790569
207706   415   206    0.774597
158811   317   311    0.750000
147808   295   308    0.746004
99116    198   116    0.707107
219981   439   481    0.707107

In [34]:
reviews[108]

'"These packs are so overpriced for what you get, and you need packs 3-5 if you want access to the player aids for the Factions expansion. The base game of Alien Frontiers just plays so much smoother than adding Factions with these expansion packs."\n'

In [35]:
reviews[2]

'You need expansion packs 3-5 if you want access to the player aids for the Factions expansion. The base game of Alien Frontiers just plays so much smoother than adding Factions with the expansion packs. All this will do is pigeonhole you into a certain path to victory.\n'

## Document Similarities Using Word2Vec (Bag of Words Approach)

In [37]:
vectors = [nlp(review).vector for review in reviews[:500]]

In [45]:
import numpy as np
word2vec_doc_similarities = pd.DataFrame(cosine_similarity(np.array(vectors)))
word2vec_doc_similarities_table = word2vec_doc_similarities.rename_axis(
    "doc1").rename_axis("doc2", axis=1).stack().reset_index()

word2vec_doc_similarities_table.columns = ["doc1", "doc2", "similarity"]
word2vec_doc_similarities_table = word2vec_doc_similarities_table[
    word2vec_doc_similarities_table["similarity"] < 0.99]

In [48]:
word2vec_doc_similarities_table.sort_values(by="similarity", ascending=False).drop_duplicates(
    subset="similarity", keep="first").head(10)

doc1  doc2  similarity
236720   473   220    0.976603
222914   445   414    0.974119
55082    110    82    0.971740
151720   303   220    0.970441
207493   414   493    0.970324
51582    103    82    0.969886
24202     48   202    0.969799
22610     45   110    0.969380
187794   375   294    0.968992
10526     21    26    0.968710